import { ThemeConfig } from 'antd';

/** Ant Design Theme Token ← CSS 变量（见 styles/variables.less / design.md） */
const antTheme: ThemeConfig = {
  token: {
    colorPrimary: 'var(--c-primary)',
    colorInfo: 'var(--c-info)',
    colorSuccess: 'var(--c-success)',
    colorWarning: 'var(--c-warning)',
    colorError: 'var(--c-error)',
    colorText: 'var(--c-ink)',
    colorTextSecondary: 'var(--c-ink-2)',
    colorTextTertiary: 'var(--c-ink-3)',
    colorTextDisabled: 'var(--c-ink-4)',
    colorBorder: 'var(--c-border)',
    colorBorderSecondary: 'var(--c-border-light)',
    colorBgLayout: 'var(--c-bg)',
    colorBgContainer: 'var(--c-surface)',
    colorBgElevated: 'var(--c-surface)',
    colorLink: 'var(--c-primary)',
    colorLinkHover: 'var(--c-primary-hover)',
    borderRadius: 6,
    borderRadiusLG: 10,
    borderRadiusSM: 4,
    borderRadiusXS: 4,
    fontFamily: 'var(--font-body)',
    fontFamilyCode: 'var(--font-mono)',
    fontSize: 14,
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
    motionDurationFast: '0.12s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.26s',
    boxShadow: 'var(--shadow-card)',
    boxShadowSecondary: 'var(--shadow-drop)',
  },
  components: {
    Progress: {
      remainingColor: 'var(--c-border)',
      lineBorderRadius: 9999,
    },
    Button: {
      fontWeight: 500,
      paddingInline: 18,
      paddingInlineSM: 12,
      paddingInlineLG: 28,
      iconGap: 6,
      defaultBg: 'var(--c-surface)',
      defaultBorderColor: 'var(--c-border)',
      defaultColor: 'var(--c-ink)',
      contentFontSize: 13,
      contentFontSizeLG: 15,
      contentFontSizeSM: 12,
      defaultShadow: 'none',
      primaryShadow: 'none',
      borderRadius: 6,
      borderRadiusLG: 10,
      colorPrimary: 'var(--c-primary)',
      colorPrimaryHover: 'var(--c-primary-hover)',
      colorPrimaryActive: 'var(--c-primary-hover)',
    },
    Tag: {
      defaultBg: 'var(--c-surface-2)',
      defaultColor: 'var(--c-ink-2)',
      borderRadiusSM: 9999,
    },
    Input: {
      inputFontSize: 14,
      inputFontSizeLG: 14,
      paddingInline: 12,
      paddingInlineLG: 12,
      paddingBlock: 9,
      paddingBlockLG: 9,
      hoverBorderColor: 'var(--c-ink-3)',
      activeBorderColor: 'var(--c-primary)',
      activeShadow: '0 0 0 3px rgba(0, 69, 176, 0.12)',
      borderRadius: 6,
    },
    InputNumber: {
      inputFontSizeLG: 14,
      paddingInlineLG: 12,
      paddingBlockLG: 9,
      borderRadius: 6,
    },
    Select: {
      hoverBorderColor: 'var(--c-ink-3)',
      activeBorderColor: 'var(--c-primary)',
      optionSelectedBg: 'var(--c-primary-light)',
      optionActiveBg: 'var(--c-surface-2)',
      selectorBg: 'var(--c-surface)',
      borderRadius: 6,
      controlHeight: 36,
    },
    Radio: {
      wrapperMarginInlineEnd: 6,
    },
    Table: {
      borderColor: 'var(--c-border)',
      /* 表头与数据行同底色，避免灰头白身分层 */
      headerBg: 'var(--c-surface)',
      headerColor: 'var(--c-ink-2)',
      headerSplitColor: 'transparent',
      rowHoverBg: 'var(--c-surface-2)',
      rowSelectedBg: 'var(--c-primary-light)',
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      cellPaddingInlineMD: 16,
      borderRadius: 10,
    },
    Pagination: {
      /* 选中页用浅底+主色字，避免 navy 实心底与链接色叠成异常 */
      itemActiveBg: 'var(--c-primary-light)',
      itemSize: 32,
    },
    Badge: {
      statusSize: 6,
    },
    Segmented: {
      trackPadding: 3,
      trackBg: 'var(--c-surface-2)',
      itemSelectedBg: 'var(--c-primary)',
      itemSelectedColor: '#fff',
      itemHoverColor: 'var(--c-ink-2)',
    },
    DatePicker: {
      activeBg: 'var(--c-surface)',
      hoverBg: 'var(--c-surface)',
      borderRadius: 6,
    },
    Alert: {
      defaultPadding: '12px 16px',
      borderRadiusLG: 6,
      colorInfoBg: 'var(--c-info-bg)',
      colorInfoBorder: 'transparent',
      colorSuccessBg: 'var(--c-success-bg)',
      colorSuccessBorder: 'transparent',
      colorWarningBg: 'var(--c-warning-bg)',
      colorWarningBorder: 'transparent',
      colorErrorBg: 'var(--c-error-bg)',
      colorErrorBorder: 'transparent',
    },
    Modal: {
      borderRadiusLG: 16,
      contentBg: 'var(--c-surface)',
      headerBg: 'var(--c-surface)',
    },
    Card: {
      borderRadiusLG: 10,
      paddingLG: 20,
    },
    Menu: {
      itemBorderRadius: 6,
      itemHeight: 36,
    },
    /* colorPrimary 为 CSS 变量时派生不出浅底，选中会变成实心 navy 导致深色字不可读 */
    Tree: {
      nodeSelectedBg: 'var(--c-primary-light)',
      nodeHoverBg: 'var(--c-surface-2)',
      directoryNodeSelectedBg: 'var(--c-primary-light)',
      directoryNodeSelectedColor: 'var(--c-primary)',
    },
    Tooltip: {
      borderRadius: 6,
    },
    Dropdown: {
      borderRadiusLG: 10,
      paddingBlock: 4,
    },
    Skeleton: {
      gradientFromColor: 'var(--c-surface-2)',
      gradientToColor: 'var(--c-border-light)',
    },
  },
};
export default antTheme;
